namespace :import do

	desc "Import schools"
	task :schools => :environment do
		puts "Import schools..."	

		SCHOOLS = [
		{ name: "Agnes Scot University", 
		  city: "Decatur", 
		  state: "Georgia",	
		  website: "www.agnesscott.edu", 
		  total_applicants: 1340, 
		  percent_admitted: 67, 
		  percent_attending: 28, 
		  range_sat_cr: "500-600", 
		  range_sat_math: "510-650", 
		  range_sat_writing: "520-650", 
		  range_act_comp: "22-28", 
		  average_hs_gpa: "3.59", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.collegeclasses.com/news/wp-content/uploads/2013/11/Agnes-Scott-College-Main-Hall.jpg" },

		{ name: "Albion College", 
		  city: "East Porter", 
		  state: "Michigan",	
		  website: "www.albion.edu", 
		  total_applicants: 4430, 
		  percent_admitted: 56, 
		  percent_attending: 14,
		  range_sat_cr: "520-580", 
		  range_sat_math: "510-590", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-28", 
		  average_hs_gpa: "3.50", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://odk.org/wp-content/uploads/2014/05/Albion-College.jpg" },

		{ name: "Alfred University", 
		  city: "Alfred", 
		  state: "New York",	
		  website: "www.alfred.edu", 
		  total_applicants: 3417, 
		  percent_admitted: 70,	
		  percent_attending: 22, 
		  range_sat_cr: "490-590", 
		  range_sat_math: "510-610", 
		  range_sat_writing: "460-570", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.18", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/f/ff/Alfred_University_Powell_Campus_Center.jpg" },

		{ name: "Allegheny College", 
		  city: "Meadville", 
		  state: "Pennsylvania",	
		  website: "www.allegheny.edu", 
		  total_applicants: 4512, 
		  percent_admitted: 65,	
		  percent_attending: 21, 
		  range_sat_cr: "530-640", 
		  range_sat_math: "540-650", 
		  range_sat_writing: "520-630", 
		  range_act_comp: "23-29", 
		  average_hs_gpa: "3.74", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://sitesmedia.s3.amazonaws.com/gatorblogs/files/2011/04/IMG_09531.jpg" },

		{ name: "American University", 
		  city: "Washington", 
		  state: "D.C.",	
		  website: "www.american.edu", 
		  total_applicants: 17545, 
		  percent_admitted: 41,	
		  percent_attending: 21, 
		  range_sat_cr: "590-690", 
		  range_sat_math: "570-660", 
		  range_sat_writing: "580-680", 
		  range_act_comp: "26-30", 
		  average_hs_gpa: "3.74", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://cdn.firstwefeast.com/assets/2014/03/128664-050-109142C5.jpg" }, 

		{ name: "Amherst College", 
		  city: "Amherst", 
		  state: "Massachusetts",	
		  website: "www.amherst.edu", 
		  total_applicants: 7927, 
		  percent_admitted: 14,	
		  percent_attending: 41, 
		  range_sat_cr: "670-760", 
		  range_sat_math: "680-770", 
		  range_sat_writing: "670-760", 
		  range_act_comp: "30-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/e/e4/Amherst_College_Main_Quad.jpg" },

		{ name: "Angelo State University", 
		  city: "San Angelo", 
		  state: "Texas",	
		  website: "www.angelo.edu", 
		  total_applicants: 2599, 
		  percent_admitted: 80,	
		  percent_attending: 58, 
		  range_sat_cr: "420-520", 
		  range_sat_math: "440-540", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "18-23", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://studyusa.com/images/ArticleImage-286-en_1.jpg" },

		{ name: "Arizona State University", 
		  city: "Tempe", 
		  state: "Arizona",	
		  website: "www.asu.edu", 
		  total_applicants: 35294, 
		  percent_admitted: 76,	
		  percent_attending: 38, 
		  range_sat_cr: "480-610", 
		  range_sat_math: "500-630", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "21-27", 
		  average_hs_gpa: "3.39", 
		  superscore_sat: "no", 
		  superscore_act: "no", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/e/e8/Asu_campus_1.jpg" },

		{ name: "Assumption College", 
		  city: "Worcester", 
		  state: "Massachusetts",	
		  website: "www.assumption.edu", 
		  total_applicants: 4659, 
		  percent_admitted: 74,	
		  percent_attending: 15, 
		  range_sat_cr: "510-595", 
		  range_sat_math: "510-620", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.32", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://www.assumption.edu/sites/default/files/styles/home_page_slider_image/public/homeHeroAdmissions_0.jpg?itok=CRXK4GWj" },

		{ name: "Auburn University", 
		  city: "Auburn", 
		  state: "Alabama",	
		  website: "www.auburn.edu", 
		  total_applicants: 15745, 
		  percent_admitted: 83,	
		  percent_attending: 29, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "540-650", 
		  range_sat_writing: "510-620", 
		  range_act_comp: "24-30", 
		  average_hs_gpa: "3.74", 
		  superscore_sat: "no", 
		  superscore_act: "no", 
		  image_url: "http://images.bwbx.io/cms/2013-06-21/0621_auburn_630x420.jpg" },


		{ name: "Austin College", 
		  city: "Sherman", 
		  state: "Texas",	
		  website: "www.austincollege.edu", 
		  total_applicants: 3138, 
		  percent_admitted: 59,	
		  percent_attending: 12, 
		  range_sat_cr: "540-660", 
		  range_sat_math: "560-670", 
		  range_sat_writing: "520-630", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.56", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.ctcl.org/sites/default/files/austin12.jpg" },

		{ name: "Babson College", 
		  city: "Babson Park", 
		  state: "Massachusetts",	
		  website: "www.babson.edu", 
		  total_applicants: 6086, 
		  percent_admitted: 28,	
		  percent_attending: 28, 
		  range_sat_cr: "550-640", 
		  range_sat_math: "610-700", 
		  range_sat_writing: "580-670", 
		  range_act_comp: "26-29", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://www.capitoldebate.com/wp-content/uploads/2014/05/BABSON_AERIALX600.jpg" },

		{ name: "Bard College", 
		  city: "Annandale-on-Hudson", 
		  state: "New York",	
		  website: "www.bard.edu", 
		  total_applicants: 5466, 
		  percent_admitted: 38,	
		  percent_attending: 24, 
		  range_sat_cr: "600-710", 
		  range_sat_math: "570-670", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.50", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.campusexplorer.com/media/560x420/Bard-College-8F584854.jpg" },

		{ name: "Bard College at Simon's Rock", 
		  city: "Great Barrington", 
		  state: "Massachusetts",	
		  website: "www.simons-rock.edu", 
		  total_applicants: 218, 
		  percent_admitted: 92,	
		  percent_attending: 72, 
		  range_sat_cr: "690-750", 
		  range_sat_math: "600-710", 
		  range_sat_writing: "620-710", 
		  range_act_comp: "24-27", 
		  average_hs_gpa: "3.71", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://i2.cdn.turner.com/dr/hln/www/release/sites/default/files/static/images/5655607835_85e9b61621_o.jpg" },

		{ name: "Barnard College", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.barnard.edu", 
		  total_applicants: 5606, 
		  percent_admitted: 21,	
		  percent_attending: 50, 
		  range_sat_cr: "620-730", 
		  range_sat_math: "620-710", 
		  range_sat_writing: "650-740", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "3.86", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.themontclarion.org/wordpress/wp-content/uploads/2013/02/barnard-college-campus.jpg" },

		{ name: "Bates College", 
		  city: "Lewiston", 
		  state: "Maine",	
		  website: "www.bates.edu", 
		  total_applicants: 4906, 
		  percent_admitted: 27,	
		  percent_attending: 39, 
		  range_sat_cr: "630-720", 
		  range_sat_math: "630-710", 
		  range_sat_writing: "643-720", 
		  range_act_comp: "30-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.bloomberg.com/ss/08/10/1029_college_costs/image/bates.jpg" },

		{ name: "Baylor University", 
		  city: "Waco", 
		  state: "Texas",	
		  website: "www.baylor.edu", 
		  total_applicants: 29249, 
		  percent_admitted: 57,	
		  percent_attending: 19, 
		  range_sat_cr: "550-660", 
		  range_sat_math: "570-670", 
		  range_sat_writing: "530-640", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://www.bloomberg.com/ss/09/09/0915_college_prowler_ranking/image/045_baylor.jpg" },

		{ name: "Becker College", 
		  city: "Worcester", 
		  state: "Massachusetts",	
		  website: "www.becker.edu", 
		  total_applicants: 3936, 
		  percent_admitted: 63,	
		  percent_attending: 15, 
		  range_sat_cr: "450-550", 
		  range_sat_math: "440-570", 
		  range_sat_writing: "430-520", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.02", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://colleges.usnews.rankingsandreviews.com/img/college-photo_7966..jpg" },

		{ name: "Bellarmine University", 
		  city: "Louisville", 
		  state: "Kentucky",	
		  website: "www.bellarmine.edu", 
		  total_applicants: 4160, 
		  percent_admitted: 95,	
		  percent_attending: 17, 
		  range_sat_cr: "490-590", 
		  range_sat_math: "490-590", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.53", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.bellarmine.edu/sf-images/default-source/photo-tour/quad-large.png?sfvrsn=0" },

		{ name: "Beloit College", 
		  city: "Beloit", 
		  state: "Wisconsin",	
		  website: "www.beloit.edu", 
		  total_applicants: 2253, 
		  percent_admitted: 68,	
		  percent_attending: 20, 
		  range_sat_cr: "550-710", 
		  range_sat_math: "540-660", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "24-30", 
		  average_hs_gpa: "3.43", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://www.visitbeloit.com/uploads//college/beloitcollege-top.jpg" },

		{ name: "Bennington College", 
		  city: "Bennington", 
		  state: "Vermont",	
		  website: "www.bennington.edu", 
		  total_applicants: 1236, 
		  percent_admitted: 63,	
		  percent_attending: 25, 
		  range_sat_cr: "620-720", 
		  range_sat_math: "560-660", 
		  range_sat_writing: "610-700", 
		  range_act_comp: "26-30", 
		  average_hs_gpa: "3.53", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.sparrowhall.com/blog/wp-content/uploads/2011/12/bennington-college-commons-sparrow-hall-web.jpg" },

		{ name: "Bentley University", 
		  city: "Waltham", 
		  state: "Massachusetts",	
		  website: "www.bentley.edu", 
		  total_applicants: 7493, 
		  percent_admitted: 44,	
		  percent_attending: 30, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "600-680", 
		  range_sat_writing: "550-650", 
		  range_act_comp: "26-30", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.addinc.com/webimages/projects/BentleyDormRoom_4_201202091107860.jpg" },

		{ name: "Berea College", 
		  city: "Berea", 
		  state: "Kentucky",	
		  website: "www.berea.edu", 
		  total_applicants: 1606, 
		  percent_admitted: 34,	
		  percent_attending: 72, 
		  range_sat_cr: "510-630", 
		  range_sat_math: "513-610", 
		  range_sat_writing: "483-610", 
		  range_act_comp: "22-26", 
		  average_hs_gpa: "3.42", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://bcnow.berea.edu/wp-content/uploads/2011/04/campus-shot.jpg" },

		{ name: "Boston College", 
		  city: "Chestnut Hill", 
		  state: "Massachusetts",	
		  website: "www.bc.edu", 
		  total_applicants: 24538, 
		  percent_admitted: 32,	
		  percent_attending: 28, 
		  range_sat_cr: "620-710", 
		  range_sat_math: "650-740", 
		  range_sat_writing: "640-730", 
		  range_act_comp: "30-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://cdn1.bostonmagazine.com/wp-content/uploads/2013/04/boston-college.jpg" },

		{ name: "Boston University", 
		  city: "Boston", 
		  state: "Massachusetts",	
		  website: "www.bu.edu", 
		  total_applicants: 52705, 
		  percent_admitted: 37,	
		  percent_attending: 20, 
		  range_sat_cr: "570-670", 
		  range_sat_math: "620-720", 
		  range_sat_writing: "600-690", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "3.59", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://neutrino2014.bu.edu/files/2013/08/503678580503_0_bg.jpg" },

		{ name: "Bowdoin College", 
		  city: "Brunswick", 
		  state: "Maine",	
		  website: "www.bowdoin.edu", 
		  total_applicants: 7052, 
		  percent_admitted: 15,	
		  percent_attending: 47, 
		  range_sat_cr: "680-760", 
		  range_sat_math: "680-750", 
		  range_sat_writing: "690-770", 
		  range_act_comp: "30-33", 
		  average_hs_gpa: "3.80", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.bowdoin.edu/government/images/bowdoin-hubbard-hall-spring-2012.jpg" },

		{ name: "Bradley University", 
		  city: "Peoira", 
		  state: "Illinois",	
		  website: "www.bradley.edu", 
		  total_applicants: 7562, 
		  percent_admitted: 63,	
		  percent_attending: 21, 
		  range_sat_cr: "520-660", 
		  range_sat_math: "510-650", 
		  range_sat_writing: "520-620", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.69", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "" },

		{ name: "Brandeis University", 
		  city: "Waltham", 
		  state: "Massachusetts",	
		  website: "www.brandeis.edu", 
		  total_applicants: 9496, 
		  percent_admitted: 37,	
		  percent_attending: 24, 
		  range_sat_cr: "600-710", 
		  range_sat_math: "630-760", 
		  range_sat_writing: "620-720", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "3.87", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/5/5d/Bradley_University_Bradley_Hall.jpg" },

		{ name: "Brigham Young University", 
		  city: "Provo", 
		  state: "Utah",	
		  website: "www.byu.edu", 
		  total_applicants: 11603, 
		  percent_admitted: 49,	
		  percent_attending: 78, 
		  range_sat_cr: "570-680", 
		  range_sat_math: "580-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "26-31", 
		  average_hs_gpa: "3.80", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/c/cf/BYU_Campus_North.jpg" },

		{ name: "Brown University", 
		  city: "Providence", 
		  state: "Rhode Island",	
		  website: "www.brown.edu", 
		  total_applicants: 28919, 
		  percent_admitted: 9,	
		  percent_attending: 58, 
		  range_sat_cr: "660-760", 
		  range_sat_math: "670-780", 
		  range_sat_writing: "670-770", 
		  range_act_comp: "29-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.brown.edu/admission/undergraduate/sites/brown.edu.admission.undergraduate/files/brown_video/poster_images/admissionvideoTITLE_0.png" },

		{ name: "Bryant University", 
		  city: "Smithfield", 
		  state: "Rhode Island",	
		  website: "www.bryant.edu", 
		  total_applicants: 6013, 
		  percent_admitted: 77,	
		  percent_attending: 19, 
		  range_sat_cr: "510-590", 
		  range_sat_math: "540-630", 
		  range_sat_writing: "500-590", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.32", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://02.usjournal.com/img/bryant-fall.jpg" },

		{ name: "Bryn Mawr College", 
		  city: "Bryn Mawr", 
		  state: "Pennsylvania",	
		  website: "www.brynmawr.edu", 
		  total_applicants: 2708, 
		  percent_admitted: 40,	
		  percent_attending: 34, 
		  range_sat_cr: "600-710", 
		  range_sat_math: "610-760", 
		  range_sat_writing: "620-720", 
		  range_act_comp: "27-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://www.brynmawr.edu/homeimages/homeimageUC.jpg" },

		{ name: "Bucknell University", 
		  city: "Lewisburg", 
		  state: "Pennsylvania",	
		  website: "www.bucknell.edu", 
		  total_applicants: 7947, 
		  percent_admitted: 30,	
		  percent_attending: 40, 
		  range_sat_cr: "580-680", 
		  range_sat_math: "620-720", 
		  range_sat_writing: "600-690", 
		  range_act_comp: "27-32", 
		  average_hs_gpa: "3.54", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.bloomberg.com/ss/10/10/1028_most_expensive_colleges/image/09_bucknell.jpg" },

		{ name: "California Institute of Technology", 
		  city: "Pasadena", 
		  state: "California",	
		  website: "www.caltech.edu", 
		  total_applicants: 5535, 
		  percent_admitted: 11,	
		  percent_attending: 42, 
		  range_sat_cr: "720-800", 
		  range_sat_math: "770-800", 
		  range_sat_writing: "720-790", 
		  range_act_comp: "33-35", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/c/c0/Fountain_at_Caltech.jpg" },

		{ name: "California State University, Stanislaus", 
		  city: "Turlock", 
		  state: "California",	
		  website: "www.csustan.edu", 
		  total_applicants: 5804, 
		  percent_admitted: 74,	
		  percent_attending: 29, 
		  range_sat_cr: "400-510", 
		  range_sat_math: "410-510", 
		  range_sat_writing: "400-500", 
		  range_act_comp: "16-22", 
		  average_hs_gpa: "3.26", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "http://catalog.csustan.edu/mime/media/13/850/homepage%20photo%2011_12.JPG" },

		{ name: "Calvin College", 
		  city: "Grand Rapids", 
		  state: "Michigan",	
		  website: "www.calvin.edu", 
		  total_applicants: 4001, 
		  percent_admitted: 70,	
		  percent_attending: 36, 
		  range_sat_cr: "518-650", 
		  range_sat_math: "530-660", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-29", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "no", 
		  superscore_act: "no", 
		  image_url: "https://oldalexius.files.wordpress.com/2014/02/hekman-library-general-view-calvin-college-large.jpg" },

		{ name: "Carleton College", 
		  city: "Northfield", 
		  state: "Minnesota",	
		  website: "www.carleton.edu", 
		  total_applicants: 7045, 
		  percent_admitted: 21,	
		  percent_attending: 36, 
		  range_sat_cr: "660-750", 
		  range_sat_math: "680-770", 
		  range_sat_writing: "660-750", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/9/98/Carleton_College_Aerial.jpg" },

		{ name: "Carngie Mellon University", 
		  city: "Pittsburgh", 
		  state: "Pennsylvania",	
		  website: "www.cmu.edu", 
		  total_applicants: 18884, 
		  percent_admitted: 25,	
		  percent_attending: 30, 
		  range_sat_cr: "640-740", 
		  range_sat_math: "700-790", 
		  range_sat_writing: "650-750", 
		  range_act_comp: "30-34", 
		  average_hs_gpa: "3.72", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://www.cmu.edu/multimedia/images/wallpapers/cmu-student-pride.jpg" },

		{ name: "Case Western Reserve University", 
		  city: "Cleveland", 
		  state: "Ohio",	
		  website: "www.case.edu", 
		  total_applicants: 18418, 
		  percent_admitted: 42,	
		  percent_attending: 16, 
		  range_sat_cr: "600-720", 
		  range_sat_math: "670-760", 
		  range_sat_writing: "620-710", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://upload.wikimedia.org/wikipedia/commons/3/38/Case_western_reserve_campus_2005.jpg" },

		{ name: "Catawba College", 
		  city: "Salisbury", 
		  state: "North Carolina",	
		  website: "www.catawba.edu", 
		  total_applicants: 3226, 
		  percent_admitted: 41,	
		  percent_attending: 26, 
		  range_sat_cr: "420-540", 
		  range_sat_math: "430-550", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "18-23", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "yes", 
		  superscore_act: "no", 
		  image_url: "http://cdn87.psbin.com/img/mw=620/mh=540/cr=y/d=c2ue5/senroszbidwg49re.jpg" },

		{ name: "The Catholic University of America", 
		  city: "Washington", 
		  state: "D.C.",	
		  website: "www.cua.edu", 
		  total_applicants: 6298, 
		  percent_admitted: 60,	
		  percent_attending: 22, 
		  range_sat_cr: "500-610", 
		  range_sat_math: "510-610", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.33", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Centenary College of Louisiana", 
		  city: "Shreveport", 
		  state: "Louisiana",	
		  website: "www.centenary.edu", 
		  total_applicants: 933, 
		  percent_admitted: 64,	
		  percent_attending: 26, 
		  range_sat_cr: "490-620", 
		  range_sat_math: "430-780", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.53", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Centre College", 
		  city: "Danville", 
		  state: "Kentucky",	
		  website: "www.centre.edu", 
		  total_applicants: 2533, 
		  percent_admitted: 69,	
		  percent_attending: 22, 
		  range_sat_cr: "550-670", 
		  range_sat_math: "560-680", 
		  range_sat_writing: "550-670", 
		  range_act_comp: "26-31", 
		  average_hs_gpa: "3.70", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Champlain College", 
		  city: "Burlington", 
		  state: "Vermont",	
		  website: "www.champlain.edu", 
		  total_applicants: 3077, 
		  percent_admitted: 85,	
		  percent_attending: 25, 
		  range_sat_cr: "500-610", 
		  range_sat_math: "490-590", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "20-25", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Chapman University", 
		  city: "Orange", 
		  state: "California",	
		  website: "www.chapman.edu", 
		  total_applicants: 11750, 
		  percent_admitted: 45,	
		  percent_attending: 25, 
		  range_sat_cr: "550-640", 
		  range_sat_math: "570-660", 
		  range_sat_writing: "560-650", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.68", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Christopher Newport University", 
		  city: "Newport News", 
		  state: "Virginia",	
		  website: "www.cnu.edu", 
		  total_applicants: 7016, 
		  percent_admitted: 59,	
		  percent_attending: 31, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "530-620", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.70", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "City University of New York - Baruch College", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.baruch.cuny.edu", 
		  total_applicants: 19423, 
		  percent_admitted: 27,	
		  percent_attending: 24, 
		  range_sat_cr: "530-630", 
		  range_sat_math: "600-700", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.21", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "City University of New York - Brooklyn College", 
		  city: "Brooklyn", 
		  state: "New York",	
		  website: "www.brooklyn.cuny.edu", 
		  total_applicants: 20145, 
		  percent_admitted: 34,	
		  percent_attending: 18, 
		  range_sat_cr: "470-570", 
		  range_sat_math: "510-600", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.28", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "City University of New York - City College", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.ccny.cuny.edu", 
		  total_applicants: 26628, 
		  percent_admitted: 34,	
		  percent_attending: 16, 
		  range_sat_cr: "450-510", 
		  range_sat_math: "520-580", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "City University of New York - Hunter College", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.hunter.cuny.edu", 
		  total_applicants: 30708, 
		  percent_admitted: 31,	
		  percent_attending: 21, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "550-650", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "City University of New York - Queens College", 
		  city: "Queens", 
		  state: "New York",	
		  website: "www.qc.cuny.edu", 
		  total_applicants: 18518, 
		  percent_admitted: 36,	
		  percent_attending: 20, 
		  range_sat_cr: "477-570", 
		  range_sat_math: "540-610", 
		  range_sat_writing: "460-570", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Claremont McKenna College", 
		  city: "Claremont", 
		  state: "California",	
		  website: "www.cmc.edu", 
		  total_applicants: 5058, 
		  percent_admitted: 14,	
		  percent_attending: 42, 
		  range_sat_cr: "650-750", 
		  range_sat_math: "660-760", 
		  range_sat_writing: "660-740", 
		  range_act_comp: "29-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Clarkson University", 
		  city: "Potsdam", 
		  state: "New York",	
		  website: "www.clarkson.edu", 
		  total_applicants: 6747, 
		  percent_admitted: 64,	
		  percent_attending: 18, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "570-670", 
		  range_sat_writing: "500-600", 
		  range_act_comp: "24-28", 
		  average_hs_gpa: "3.60", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Clemson University", 
		  city: "Clemson", 
		  state: "South Carolina",	
		  website: "www.clemson.edu", 
		  total_applicants: 17016, 
		  percent_admitted: 60,	
		  percent_attending: 29, 
		  range_sat_cr: "550-650", 
		  range_sat_math: "590-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "4.18", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Coe College", 
		  city: "Cedar Rapids", 
		  state: "Iowa",	
		  website: "www.coe.edu", 
		  total_applicants: 2972, 
		  percent_admitted: 62,	
		  percent_attending: 21, 
		  range_sat_cr: "493-693", 
		  range_sat_math: "495-670", 
		  range_sat_writing: "458-660", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.62", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Colby College", 
		  city: "Waterville", 
		  state: "Maine",	
		  website: "www.colby.edu", 
		  total_applicants: 5234, 
		  percent_admitted: 29,	
		  percent_attending: 32, 
		  range_sat_cr: "610-710", 
		  range_sat_math: "630-720", 
		  range_sat_writing: "610-710", 
		  range_act_comp: "29-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Colgate University", 
		  city: "Hamilton", 
		  state: "New York",	
		  website: "www.colgate.edu", 
		  total_applicants: 8375, 
		  percent_admitted: 26,	
		  percent_attending: 34, 
		  range_sat_cr: "620-720", 
		  range_sat_math: "650-730", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "30-32", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "College of the Atlantic", 
		  city: "Bar Harbor", 
		  state: "Maine",	
		  website: "www.coa.edu", 
		  total_applicants: 455, 
		  percent_admitted: 73,	
		  percent_attending: 31, 
		  range_sat_cr: "580-690", 
		  range_sat_math: "530-640", 
		  range_sat_writing: "580-650", 
		  range_act_comp: "25-33", 
		  average_hs_gpa: "3.56", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "College of Charleston", 
		  city: "Charleston", 
		  state: "South Carolina",	
		  website: "www.cofc.edu", 
		  total_applicants: 11532, 
		  percent_admitted: 72,	
		  percent_attending: 25, 
		  range_sat_cr: "530-630", 
		  range_sat_math: "520-610", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-37", 
		  average_hs_gpa: "3.90", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "College of the Holy Cross", 
		  city: "Worcester", 
		  state: "Massachusetts",	
		  website: "www.holycross.edu", 
		  total_applicants: 7115, 
		  percent_admitted: 33,	
		  percent_attending: 31, 
		  range_sat_cr: "610-690", 
		  range_sat_math: "610-700", 
		  range_sat_writing: "610-700", 
		  range_act_comp: "28-31", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The College of Idaho", 
		  city: "Caldwell", 
		  state: "Idaho",	
		  website: "www.collegeofidaho.edu", 
		  total_applicants: 1388, 
		  percent_admitted: 65,	
		  percent_attending: 32, 
		  range_sat_cr: "470-630", 
		  range_sat_math: "480-600", 
		  range_sat_writing: "460-600", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.64", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The College of New Jersey", 
		  city: "Ewing", 
		  state: "New Jersey",	
		  website: "www.tcnj.edu", 
		  total_applicants: 11145, 
		  percent_admitted: 43,	
		  percent_attending: 29, 
		  range_sat_cr: "550-660", 
		  range_sat_math: "580-680", 
		  range_sat_writing: "560-670", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "College of the Ozarks", 
		  city: "Point Lookout", 
		  state: "Missouri",	
		  website: "www.cofo.edu", 
		  total_applicants: 3050, 
		  percent_admitted: 12,	
		  percent_attending: 96, 
		  range_sat_cr: "510-560", 
		  range_sat_math: "450-548", 
		  range_sat_writing: "495-548", 
		  range_act_comp: "20-25", 
		  average_hs_gpa: "3.63", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "College of Saint Benedict/Saint John's University", 
		  city: "St. Joseph", 
		  state: "Minnesota",	
		  website: "www.csbsju.edu", 
		  total_applicants: 3824, 
		  percent_admitted: 75,	
		  percent_attending: 36, 
		  range_sat_cr: "470-600", 
		  range_sat_math: "475-620", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.59", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The College of William & Mary", 
		  city: "Williamsburg", 
		  state: "Virginia",	
		  website: "www.wm.edu", 
		  total_applicants: 13660, 
		  percent_admitted: 32,	
		  percent_attending: 33, 
		  range_sat_cr: "630-740", 
		  range_sat_math: "620-720", 
		  range_sat_writing: "620-720", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "4.00", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The College of Wooster", 
		  city: "Wooster", 
		  state: "Ohio",	
		  website: "www.wooster.edu", 
		  total_applicants: 5583, 
		  percent_admitted: 56,	
		  percent_attending: 18, 
		  range_sat_cr: "550-670", 
		  range_sat_math: "550-660", 
		  range_sat_writing: "560-650", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Colorado College", 
		  city: "Colorado Springs", 
		  state: "Colorado",	
		  website: "www.coloradocollege.edu", 
		  total_applicants: 5780, 
		  percent_admitted: 22,	
		  percent_attending: 41, 
		  range_sat_cr: "610-710", 
		  range_sat_math: "610-720", 
		  range_sat_writing: "620-700", 
		  range_act_comp: "27-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Colorado State University", 
		  city: "Fort Collins", 
		  state: "Colorado",	
		  website: "www.colostate.edu", 
		  total_applicants: 17970, 
		  percent_admitted: 77,	
		  percent_attending: 32, 
		  range_sat_cr: "510-620", 
		  range_sat_math: "510-630", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.61", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Columbia University", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.columbia.edu", 
		  total_applicants: 33531, 
		  percent_admitted: 7,	
		  percent_attending: 61, 
		  range_sat_cr: "700-780", 
		  range_sat_math: "700-790", 
		  range_sat_writing: "690-780", 
		  range_act_comp: "32-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Connecticut College", 
		  city: "New London", 
		  state: "Connecticut",	
		  website: "www.conncoll.edu", 
		  total_applicants: 4837, 
		  percent_admitted: 36,	
		  percent_attending: 29, 
		  range_sat_cr: "620-710", 
		  range_sat_math: "615-700", 
		  range_sat_writing: "640-725", 
		  range_act_comp: "28-31", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The Cooper Union for the Advancement of Science and Art", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.cooper.edu", 
		  total_applicants: 3193, 
		  percent_admitted: 8,	
		  percent_attending: 75, 
		  range_sat_cr: "610-710", 
		  range_sat_math: "610-780", 
		  range_sat_writing: "610-730", 
		  range_act_comp: "28-33", 
		  average_hs_gpa: "3.60", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Cornell College", 
		  city: "Mount Vernon", 
		  state: "Iowa",	
		  website: "www.cornellcollege.edu", 
		  total_applicants: 2498, 
		  percent_admitted: 59,	
		  percent_attending: 18, 
		  range_sat_cr: "520-670", 
		  range_sat_math: "510-650", 
		  range_sat_writing: "510-630", 
		  range_act_comp: "23-29", 
		  average_hs_gpa: "3.54", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Cornell University", 
		  city: "Ithaca", 
		  state: "New York",	
		  website: "www.cornell.edu", 
		  total_applicants: 39999, 
		  percent_admitted: 16,	
		  percent_attending: 52, 
		  range_sat_cr: "640-740", 
		  range_sat_math: "680-780", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "30-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Creighton University", 
		  city: "Omaha", 
		  state: "Nebraska",	
		  website: "www.creighton.edu", 
		  total_applicants: 5336, 
		  percent_admitted: 77,	
		  percent_attending: 24, 
		  range_sat_cr: "520-640", 
		  range_sat_math: "540-660", 
		  range_sat_writing: "500-620", 
		  range_act_comp: "24-30", 
		  average_hs_gpa: "3.75", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Dartmouth College", 
		  city: "Hanover", 
		  state: "New Hampshire",	
		  website: "www.dartmouth.edu", 
		  total_applicants: 22428, 
		  percent_admitted: 10,	
		  percent_attending: 48, 
		  range_sat_cr: "680-780", 
		  range_sat_math: "680-780", 
		  range_sat_writing: "680-780", 
		  range_act_comp: "30-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Davidson College", 
		  city: "Davidson", 
		  state: "North Carolina",	
		  website: "www.davidson.edu", 
		  total_applicants: 4745, 
		  percent_admitted: 26,	
		  percent_attending: 40, 
		  range_sat_cr: "630-730", 
		  range_sat_math: "600-710", 
		  range_sat_writing: "610-710", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "3.98", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Deep Springs College", 
		  city: "Dyer", 
		  state: "Nevada",	
		  website: "www.deepsprings.edu", 
		  total_applicants: 170, 
		  percent_admitted: 7,	
		  percent_attending: 100, 
		  range_sat_cr: "750-800", 
		  range_sat_math: "700-800", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Denison University", 
		  city: "Granville", 
		  state: "Ohio",	
		  website: "www.denison.edu", 
		  total_applicants: 4757, 
		  percent_admitted: 50,	
		  percent_attending: 27, 
		  range_sat_cr: "600-720", 
		  range_sat_math: "600-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "3.50", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "DePaul University", 
		  city: "Chicago", 
		  state: "Illinois",	
		  website: "www.depaul.edu", 
		  total_applicants: 19957, 
		  percent_admitted: 60,	
		  percent_attending: 20, 
		  range_sat_cr: "530-630", 
		  range_sat_math: "520-630", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.65", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "DePauw University", 
		  city: "Greencastle", 
		  state: "Indiana",	
		  website: "www.depauw.edu", 
		  total_applicants: 5204, 
		  percent_admitted: 60,	
		  percent_attending: 21, 
		  range_sat_cr: "520-650", 
		  range_sat_math: "550-680", 
		  range_sat_writing: "530-630", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.75", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Dickinson College", 
		  city: "Carlisle", 
		  state: "Pennsylvania",	
		  website: "www.dickinson.edu", 
		  total_applicants: 5826, 
		  percent_admitted: 44,	
		  percent_attending: 24, 
		  range_sat_cr: "590-675", 
		  range_sat_math: "600-690", 
		  range_sat_writing: "590-680", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Drew University", 
		  city: "Madison", 
		  state: "New Jersey",	
		  website: "www.drew.edu", 
		  total_applicants: 3430, 
		  percent_admitted: 77,	
		  percent_attending: 15, 
		  range_sat_cr: "490-610", 
		  range_sat_math: "500-610", 
		  range_sat_writing: "500-610", 
		  range_act_comp: "21.5-27", 
		  average_hs_gpa: "3.40", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Drexel University", 
		  city: "Philadelphia", 
		  state: "Pennsylvania",	
		  website: "www.drexel.edu", 
		  total_applicants: 40586, 
		  percent_admitted: 75,	
		  percent_attending: 10, 
		  range_sat_cr: "540-640", 
		  range_sat_math: "580-680", 
		  range_sat_writing: "530-640", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.60", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Duke University", 
		  city: "Philadelphia", 
		  state: "Pennsylvania",	
		  website: "www.duke.edu", 
		  total_applicants: 30374, 
		  percent_admitted: 13,	
		  percent_attending: 42, 
		  range_sat_cr: "670-760", 
		  range_sat_math: "690-790", 
		  range_sat_writing: "680-780", 
		  range_act_comp: "30-34", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Duquesne University", 
		  city: "Pittsburgh", 
		  state: "Pennsylvania",	
		  website: "www.duq.edu", 
		  total_applicants: 6793, 
		  percent_admitted: 74,	
		  percent_attending: 31, 
		  range_sat_cr: "510-600", 
		  range_sat_math: "520-610", 
		  range_sat_writing: "500-600", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Eckerd College", 
		  city: "St. Petersburg", 
		  state: "Florida",	
		  website: "www.eckerd.edu", 
		  total_applicants: 3509, 
		  percent_admitted: 72,	
		  percent_attending: 18, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "510-600", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.34", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Elon University", 
		  city: "Elon", 
		  state: "North Carolina",	
		  website: "www.elon.edu", 
		  total_applicants: 9949, 
		  percent_admitted: 54,	
		  percent_attending: 27, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "540-610", 
		  range_sat_writing: "540-640", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.96", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Emerson College", 
		  city: "Boston", 
		  state: "Massachusetts",	
		  website: "www.drexel.edu", 
		  total_applicants: 6943, 
		  percent_admitted: 42,	
		  percent_attending: 26, 
		  range_sat_cr: "570-670", 
		  range_sat_math: "540-640", 
		  range_sat_writing: "580-670", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.59", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Emory University", 
		  city: "Atlanta", 
		  state: "Georgia",	
		  website: "www.emory.edu", 
		  total_applicants: 17678, 
		  percent_admitted: 26,	
		  percent_attending: 29, 
		  range_sat_cr: "610-710", 
		  range_sat_math: "650-760", 
		  range_sat_writing: "630-730", 
		  range_act_comp: "29-32", 
		  average_hs_gpa: "3.75", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The Evergreen State College", 
		  city: "Olympia", 
		  state: "Washington",	
		  website: "www.evergreen.edu", 
		  total_applicants: 1583, 
		  percent_admitted: 97,	
		  percent_attending: 33, 
		  range_sat_cr: "500-630", 
		  range_sat_math: "450-580", 
		  range_sat_writing: "460-590", 
		  range_act_comp: "20-27", 
		  average_hs_gpa: "3.02", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Fairfield University", 
		  city: "Fairfield", 
		  state: "Connecticut",	
		  website: "www.fairfield.edu", 
		  total_applicants: 9582, 
		  percent_admitted: 70,	
		  percent_attending: 14, 
		  range_sat_cr: "540-620", 
		  range_sat_math: "550-630", 
		  range_sat_writing: "550-640", 
		  range_act_comp: "24-28", 
		  average_hs_gpa: "3.38", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Flagler College", 
		  city: "St. Augustine", 
		  state: "Florida",	
		  website: "www.flagler.edu", 
		  total_applicants: 5396, 
		  percent_admitted: 50,	
		  percent_attending: 26, 
		  range_sat_cr: "unavailable", 
		  range_sat_math: "unavailable", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Florida Southern College", 
		  city: "Lakeland", 
		  state: "Florida",	
		  website: "www.flsouthern.edu", 
		  total_applicants: 4963, 
		  percent_admitted: 50,	
		  percent_attending: 26, 
		  range_sat_cr: "500-590", 
		  range_sat_math: "510-590", 
		  range_sat_writing: "480-580", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.62", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Florida State University", 
		  city: "Tallahassee", 
		  state: "Florida",	
		  website: "www.fsu.edu", 
		  total_applicants: 29579, 
		  percent_admitted: 57,	
		  percent_attending: 36, 
		  range_sat_cr: "560-640", 
		  range_sat_math: "550-640", 
		  range_sat_writing: "560-640", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.88", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Fordham University", 
		  city: "New York", 
		  state: "New York",	
		  website: "www.fordham.edu", 
		  total_applicants: 18161, 
		  percent_admitted: 47,	
		  percent_attending: 20, 
		  range_sat_cr: "570-670", 
		  range_sat_math: "560-660", 
		  range_sat_writing: "560-660", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.70", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Franklin & Marshall College", 
		  city: "Lancaster", 
		  state: "Pennsylvania",	
		  website: "www.fandm.edu", 
		  total_applicants: 5347, 
		  percent_admitted: 36,	
		  percent_attending: 31, 
		  range_sat_cr: "590-690", 
		  range_sat_math: "630-720", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "28-31", 
		  average_hs_gpa: "3.49", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Franklin W. Olin College of Engineering", 
		  city: "Needham", 
		  state: "Massachusetts",	
		  website: "www.olin.edu", 
		  total_applicants: 782, 
		  percent_admitted: 17,	
		  percent_attending: 63, 
		  range_sat_cr: "690-760", 
		  range_sat_math: "737.5-790", 
		  range_sat_writing: "670-780", 
		  range_act_comp: "31-34", 
		  average_hs_gpa: "3.90", 
		  superscore_sat: "yes", 
		  superscore_act: "yes", 
		  image_url: "" }, 

		{ name: "Furman University", 
		  city: "Greenville", 
		  state: "South Carolina",	
		  website: "www.furman.edu", 
		  total_applicants: 6035, 
		  percent_admitted: 64,	
		  percent_attending: 21, 
		  range_sat_cr: "550-670", 
		  range_sat_math: "580-670", 
		  range_sat_writing: "550-670", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "George Mason University", 
		  city: "Fairfax", 
		  state: "Virginia",	
		  website: "www.gmu.edu", 
		  total_applicants: 20805, 
		  percent_admitted: 62,	
		  percent_attending: 23, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "530-630", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "24-28", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "The George Washington University", 
		  city: "Washington", 
		  state: "D.C.",	
		  website: "www.gwu.edu", 
		  total_applicants: 21789, 
		  percent_admitted: 34,	
		  percent_attending: 31, 
		  range_sat_cr: "590-690", 
		  range_sat_math: "610-700", 
		  range_sat_writing: "600-700", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Georgetown University", 
		  city: "Washington", 
		  state: "D.C.",	
		  website: "www.georgetown.edu", 
		  total_applicants: 20115, 
		  percent_admitted: 17,	
		  percent_attending: 46, 
		  range_sat_cr: "650-750", 
		  range_sat_math: "660-750", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Georgia Institute of Technology", 
		  city: "Atlanta", 
		  state: "Georgia",	
		  website: "www.gatech.edu", 
		  total_applicants: 17669, 
		  percent_admitted: 41,	
		  percent_attending: 37, 
		  range_sat_cr: "620-710", 
		  range_sat_math: "670-770", 
		  range_sat_writing: "630-720", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "3.95", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Gettysburg College", 
		  city: "Gettysburg", 
		  state: "Pennsylvania",	
		  website: "www.gettysburg.edu", 
		  total_applicants: 5453, 
		  percent_admitted: 42,	
		  percent_attending: 31, 
		  range_sat_cr: "600-690", 
		  range_sat_math: "600-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Gonzaga University", 
		  city: "Spokane", 
		  state: "Washington",	
		  website: "www.gonzaga.edu", 
		  total_applicants: 7031, 
		  percent_admitted: 68,	
		  percent_attending: 26, 
		  range_sat_cr: "540-640", 
		  range_sat_math: "560-650", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.73", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Gordon College", 
		  city: "Wenham", 
		  state: "Massachusetts",	
		  website: "www.gordon.edu", 
		  total_applicants: 3843, 
		  percent_admitted: 43,	
		  percent_attending: 29, 
		  range_sat_cr: "516-653", 
		  range_sat_math: "499-639", 
		  range_sat_writing: "507-648", 
		  range_act_comp: "22-29", 
		  average_hs_gpa: "3.58", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Goucher College", 
		  city: "Baltimore", 
		  state: "Maryland",	
		  website: "www.goucher.edu", 
		  total_applicants: 3466, 
		  percent_admitted: 72,	
		  percent_attending: 16, 
		  range_sat_cr: "510-660", 
		  range_sat_math: "500-620", 
		  range_sat_writing: "510-640", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.20", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Green Mountain College", 
		  city: "Poultney", 
		  state: "Vermont",	
		  website: "www.greenmtn.edu", 
		  total_applicants: 773, 
		  percent_admitted: 76,	
		  percent_attending: 23, 
		  range_sat_cr: "480-630", 
		  range_sat_math: "440-570", 
		  range_sat_writing: "450-590", 
		  range_act_comp: "20-27", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Grinnell College", 
		  city: "Grinnell", 
		  state: "Iowa",	
		  website: "www.grinnell.edu", 
		  total_applicants: 3979, 
		  percent_admitted: 35,	
		  percent_attending: 30, 
		  range_sat_cr: "620-730", 
		  range_sat_math: "630-770", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Grove City College", 
		  city: "Grove City", 
		  state: "Pennsylvania",	
		  website: "www.gcc.edu", 
		  total_applicants: 1530, 
		  percent_admitted: 81,	
		  percent_attending: 53, 
		  range_sat_cr: "542-669", 
		  range_sat_math: "537-665", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.72", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Guilford College", 
		  city: "Greensboro", 
		  state: "North Carolina",	
		  website: "www.guilford.edu", 
		  total_applicants: 3030, 
		  percent_admitted: 68,	
		  percent_attending: 19, 
		  range_sat_cr: "460-610", 
		  range_sat_math: "480-580", 
		  range_sat_writing: "450-580", 
		  range_act_comp: "20-26", 
		  average_hs_gpa: "3.16", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hamilton College", 
		  city: "Clinton", 
		  state: "New York",	
		  website: "www.hamilton.edu", 
		  total_applicants: 5017, 
		  percent_admitted: 27,	
		  percent_attending: 36, 
		  range_sat_cr: "640-730", 
		  range_sat_math: "660-740", 
		  range_sat_writing: "650-730", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hampden-Sydney College", 
		  city: "Hampden-Sydney", 
		  state: "Virginia",	
		  website: "www.hsc.edu", 
		  total_applicants: 2623, 
		  percent_admitted: 55,	
		  percent_attending: 20, 
		  range_sat_cr: "495-600", 
		  range_sat_math: "510-615", 
		  range_sat_writing: "480-575", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.40", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hampton University", 
		  city: "Hampton", 
		  state: "Virginia",	
		  website: "www.hamptonu.edu", 
		  total_applicants: 15337, 
		  percent_admitted: 36,	
		  percent_attending: 17, 
		  range_sat_cr: "460-550", 
		  range_sat_math: "460-550", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "18-23", 
		  average_hs_gpa: "3.30", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hanover College", 
		  city: "Hanover", 
		  state: "Indiana",	
		  website: "www.hanover.edu", 
		  total_applicants: 3174, 
		  percent_admitted: 67,	
		  percent_attending: 16, 
		  range_sat_cr: "490-600", 
		  range_sat_math: "510-600", 
		  range_sat_writing: "480-570", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.67", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Harvard College", 
		  city: "Cambridge", 
		  state: "Massachusetts",	
		  website: "www.college.harvard.edu", 
		  total_applicants: 35023, 
		  percent_admitted: 6,	
		  percent_attending: 81, 
		  range_sat_cr: "700-800", 
		  range_sat_math: "710-800", 
		  range_sat_writing: "710-800", 
		  range_act_comp: "32-35", 
		  average_hs_gpa: "4.04", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Harvey Mudd College", 
		  city: "Claremont", 
		  state: "California",	
		  website: "www.hmc.edu", 
		  total_applicants: 3336, 
		  percent_admitted: 19,	
		  percent_attending: 31, 
		  range_sat_cr: "680-770", 
		  range_sat_math: "740-800", 
		  range_sat_writing: "680-760", 
		  range_act_comp: "33-35", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hillsdale College", 
		  city: "Hillsdale", 
		  state: "Michigan",	
		  website: "www.hillsdale.edu", 
		  total_applicants: 1902, 
		  percent_admitted: 50,	
		  percent_attending: 37, 
		  range_sat_cr: "640-730", 
		  range_sat_math: "590-680", 
		  range_sat_writing: "610-720", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "3.81", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hobart and William Smith Colleges", 
		  city: "Geneva", 
		  state: "New York",	
		  website: "www.hws.edu", 
		  total_applicants: 4380, 
		  percent_admitted: 50,	
		  percent_attending: 29, 
		  range_sat_cr: "560-640", 
		  range_sat_math: "560-650", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "26-29", 
		  average_hs_gpa: "3.36", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hofstra University", 
		  city: "Hempstead", 
		  state: "New York",	
		  website: "www.hofstra.edu", 
		  total_applicants: 27700, 
		  percent_admitted: 59,	
		  percent_attending: 10, 
		  range_sat_cr: "520-610", 
		  range_sat_math: "530-620", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.51", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Hollins University", 
		  city: "Roanoke", 
		  state: "Virginia",	
		  website: "www.hollins.edu", 
		  total_applicants: 824, 
		  percent_admitted: 69,	
		  percent_attending: 26, 
		  range_sat_cr: "500-640", 
		  range_sat_math: "470-580", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "21-27", 
		  average_hs_gpa: "3.50", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Howard University", 
		  city: "Washington", 
		  state: "D.C.",	
		  website: "www.howard.edu", 
		  total_applicants: 11599, 
		  percent_admitted: 57,	
		  percent_attending: 24, 
		  range_sat_cr: "470-670", 
		  range_sat_math: "460-680", 
		  range_sat_writing: "430-670", 
		  range_act_comp: "19-29", 
		  average_hs_gpa: "3.30", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Illinois Institute of Technology", 
		  city: "Chicago", 
		  state: "Illinois",	
		  website: "www.iit.edu", 
		  total_applicants: 2840, 
		  percent_admitted: 57,	
		  percent_attending: 31, 
		  range_sat_cr: "520-640", 
		  range_sat_math: "640-740", 
		  range_sat_writing: "520-640", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.64", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Illinois Wesleyan University", 
		  city: "Bloomington", 
		  state: "Illinois",	
		  website: "www.iwu.edu", 
		  total_applicants: 3556, 
		  percent_admitted: 58,	
		  percent_attending: 25, 
		  range_sat_cr: "510-620", 
		  range_sat_math: "570-740", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.73", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Indiana University - Bloomington", 
		  city: "Bloomington", 
		  state: "Indiana",	
		  website: "www.iub.edu", 
		  total_applicants: 37826, 
		  percent_admitted: 72,	
		  percent_attending: 28, 
		  range_sat_cr: "520-630", 
		  range_sat_math: "540-660", 
		  range_sat_writing: "510-620", 
		  range_act_comp: "24-30", 
		  average_hs_gpa: "3.62", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Indiana University of Pennsylvania", 
		  city: "Indiana", 
		  state: "Pennsylvania",	
		  website: "www.iup.edu", 
		  total_applicants: 9367, 
		  percent_admitted: 90,	
		  percent_attending: 32, 
		  range_sat_cr: "440-530", 
		  range_sat_math: "440-540", 
		  range_sat_writing: "420-520", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Iowa State University", 
		  city: "Ames", 
		  state: "Iowa",	
		  website: "www.iastate.edu", 
		  total_applicants: 17525, 
		  percent_admitted: 85,	
		  percent_attending: 41, 
		  range_sat_cr: "460-620", 
		  range_sat_math: "530-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-28", 
		  average_hs_gpa: "3.55", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Ithaca College", 
		  city: "Ithaca", 
		  state: "New York",	
		  website: "www.ithaca.edu", 
		  total_applicants: 15658, 
		  percent_admitted: 67,	
		  percent_attending: 17, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "540-640", 
		  range_sat_writing: "540-640", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "James Madison University", 
		  city: "Harrisonburg", 
		  state: "Virginia",	
		  website: "www.jmu.edu", 
		  total_applicants: 23400, 
		  percent_admitted: 60,	
		  percent_attending: 29, 
		  range_sat_cr: "520-620", 
		  range_sat_math: "530-620", 
		  range_sat_writing: "520-610", 
		  range_act_comp: "23-27", 
		  average_hs_gpa: "3.80", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Johns Hopkins University", 
		  city: "Baltimore", 
		  state: "Maryland",	
		  website: "www.jhu.edu", 
		  total_applicants: 20614, 
		  percent_admitted: 17,	
		  percent_attending: 37, 
		  range_sat_cr: "660-740", 
		  range_sat_math: "680-780", 
		  range_sat_writing: "660-760", 
		  range_act_comp: "31-34", 
		  average_hs_gpa: "3.74", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Juniata College", 
		  city: "Huntingdon", 
		  state: "Pennsylvania",	
		  website: "www.juniata.edu", 
		  total_applicants: 2227, 
		  percent_admitted: 74,	
		  percent_attending: 24, 
		  range_sat_cr: "520-630", 
		  range_sat_math: "520-630", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.75", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Kalamazoo College", 
		  city: "Kalamazoo", 
		  state: "Michigan",	
		  website: "www.kzoo.edu", 
		  total_applicants: 2528, 
		  percent_admitted: 67,	
		  percent_attending: 27, 
		  range_sat_cr: "550-670", 
		  range_sat_math: "540-690", 
		  range_sat_writing: "540-650", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.61", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Kansas State University", 
		  city: "Manhattan", 
		  state: "Kansas",	
		  website: "www.k-state.edu", 
		  total_applicants: 9839, 
		  percent_admitted: 96,	
		  percent_attending: 40, 
		  range_sat_cr: "unavailable", 
		  range_sat_math: "unavailable", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "21-27", 
		  average_hs_gpa: "3.47", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Kenyon College", 
		  city: "Gambier", 
		  state: "Ohio",	
		  website: "www.kenyon.edu", 
		  total_applicants: 4051, 
		  percent_admitted: 38,	
		  percent_attending: 31, 
		  range_sat_cr: "630-720", 
		  range_sat_math: "600-690", 
		  range_sat_writing: "630-730", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "3.90", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Knox College", 
		  city: "Galesburg", 
		  state: "Illinois",	
		  website: "www.knox.edu", 
		  total_applicants: 2660, 
		  percent_admitted: 75,	
		  percent_attending: 19, 
		  range_sat_cr: "560-690", 
		  range_sat_math: "550-670", 
		  range_sat_writing: "540-650", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lafayette College", 
		  city: "Easton", 
		  state: "Pennsylvania",	
		  website: "www.lafayette.edu", 
		  total_applicants: 6766, 
		  percent_admitted: 34,	
		  percent_attending: 27, 
		  range_sat_cr: "570-670", 
		  range_sat_math: "610-700", 
		  range_sat_writing: "580-690", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "3.46", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lake Forest College", 
		  city: "Lake Forest", 
		  state: "Illinois",	
		  website: "www.lakeforest.edu", 
		  total_applicants: 3684, 
		  percent_admitted: 57,	
		  percent_attending: 19, 
		  range_sat_cr: "unavailable", 
		  range_sat_math: "unavailable", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.63", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lawrence University", 
		  city: "Appleton", 
		  state: "Wisconsin",	
		  website: "www.lawrence.edu", 
		  total_applicants: 2710, 
		  percent_admitted: 73,	
		  percent_attending: 20, 
		  range_sat_cr: "560-700", 
		  range_sat_math: "580-710", 
		  range_sat_writing: "560-690", 
		  range_act_comp: "26-31", 
		  average_hs_gpa: "3.70", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Le Moyne College", 
		  city: "Syracuse", 
		  state: "New York",	
		  website: "www.lemoyne.edu", 
		  total_applicants: 5924, 
		  percent_admitted: 62,	
		  percent_attending: 17, 
		  range_sat_cr: "480-570", 
		  range_sat_math: "500-600", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "21-26", 
		  average_hs_gpa: "3.42", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lehigh University", 
		  city: "Bethlehem", 
		  state: "Pennsylvania",	
		  website: "www.lehigh.edu", 
		  total_applicants: 12589, 
		  percent_admitted: 31,	
		  percent_attending: 31, 
		  range_sat_cr: "580-670", 
		  range_sat_math: "640-740", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "28-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lewis & Clark College", 
		  city: "Portland", 
		  state: "Oregon",	
		  website: "www.lclark.edu", 
		  total_applicants: 6456, 
		  percent_admitted: 63,	
		  percent_attending: 12, 
		  range_sat_cr: "600-700", 
		  range_sat_math: "580-670", 
		  range_sat_writing: "580-690", 
		  range_act_comp: "26-31", 
		  average_hs_gpa: "3.70", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Louisiana State University", 
		  city: "Baton Rouge", 
		  state: "Louisiana",	
		  website: "www.lsu.edu", 
		  total_applicants: 16005, 
		  percent_admitted: 75,	
		  percent_attending: 46, 
		  range_sat_cr: "500-600", 
		  range_sat_math: "510-625", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.45", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Loyola Marymount University (CA)", 
		  city: "Los Angeles", 
		  state: "California",	
		  website: "www.lmu.edu", 
		  total_applicants: 11472, 
		  percent_admitted: 54,	
		  percent_attending: 22, 
		  range_sat_cr: "540-640", 
		  range_sat_math: "550-650", 
		  range_sat_writing: "550-650", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.72", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Loyola University Chicago", 
		  city: "Chicago", 
		  state: "Illinois",	
		  website: "www.luc.edu", 
		  total_applicants: 14355, 
		  percent_admitted: 91,	
		  percent_attending: 19, 
		  range_sat_cr: "520-630", 
		  range_sat_math: "530-630", 
		  range_sat_writing: "520-630", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.65", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Loyola University in Maryland", 
		  city: "Baltimore", 
		  state: "Maryland",	
		  website: "www.loyola.edu", 
		  total_applicants: 13604, 
		  percent_admitted: 58,	
		  percent_attending: 14, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "560-640", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "3.45", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Loyola University New Orleans", 
		  city: "New Orleans", 
		  state: "Louisiana",	
		  website: "www.loyno.edu", 
		  total_applicants: 6486, 
		  percent_admitted: 66,	
		  percent_attending: 21, 
		  range_sat_cr: "530-650", 
		  range_sat_math: "510-620", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "22-27", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Lynchburg College", 
		  city: "Lynchburg", 
		  state: "Virginia",	
		  website: "www.lynchburg.edu", 
		  total_applicants: 5695, 
		  percent_admitted: 64,	
		  percent_attending: 14, 
		  range_sat_cr: "450-550", 
		  range_sat_math: "440-560", 
		  range_sat_writing: "440-540", 
		  range_act_comp: "19-24", 
		  average_hs_gpa: "3.29", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Macalester College", 
		  city: "St. Paul", 
		  state: "Minnesota",	
		  website: "www.macalester.edu", 
		  total_applicants: 6683, 
		  percent_admitted: 34,	
		  percent_attending: 24, 
		  range_sat_cr: "620-740", 
		  range_sat_math: "620-720", 
		  range_sat_writing: "630-720", 
		  range_act_comp: "29-32", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Manhattanville College", 
		  city: "Purchase", 
		  state: "New York",	
		  website: "www.mville.edu", 
		  total_applicants: 3930, 
		  percent_admitted: 77,	
		  percent_attending: 18, 
		  range_sat_cr: "480-590", 
		  range_sat_math: "490-590", 
		  range_sat_writing: "470-580", 
		  range_act_comp: "22-25", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Marist College", 
		  city: "Poughkeepsie", 
		  state: "New York",	
		  website: "www.marist.edu", 
		  total_applicants: 10351, 
		  percent_admitted: 37,	
		  percent_attending: 30, 
		  range_sat_cr: "540-620", 
		  range_sat_math: "550-640", 
		  range_sat_writing: "550-640", 
		  range_act_comp: "24-28", 
		  average_hs_gpa: "3.30", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Marlboro College", 
		  city: "Marlboro", 
		  state: "Vermont",	
		  website: "www.marlboro.edu", 
		  total_applicants: 256, 
		  percent_admitted: 79,	
		  percent_attending: 24, 
		  range_sat_cr: "560-730", 
		  range_sat_math: "520-650", 
		  range_sat_writing: "530-680", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "3.11", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Marquette University", 
		  city: "Milwaukee", 
		  state: "Wisconsin",	
		  website: "www.marquette.edu", 
		  total_applicants: 23432, 
		  percent_admitted: 57,	
		  percent_attending: 15, 
		  range_sat_cr: "520-630", 
		  range_sat_math: "550-650", 
		  range_sat_writing: "520-630", 
		  range_act_comp: "25-29", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Marywood University", 
		  city: "Scranton", 
		  state: "Pennsylvania",	
		  website: "www.marywood.edu", 
		  total_applicants: 2059, 
		  percent_admitted: 70,	
		  percent_attending: 28, 
		  range_sat_cr: "470-570", 
		  range_sat_math: "480-580", 
		  range_sat_writing: "460-570", 
		  range_act_comp: "unavailable", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Massachusetts Institute of Technology", 
		  city: "Cambridge", 
		  state: "Massachusetts",	
		  website: "web.mit.edu", 
		  total_applicants: 18989, 
		  percent_admitted: 8,	
		  percent_attending: 72, 
		  range_sat_cr: "680-770", 
		  range_sat_math: "750-800", 
		  range_sat_writing: "690-780", 
		  range_act_comp: "33-35", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "McGill University", 
		  city: "Montreal", 
		  state: "Canada",	
		  website: "www.mcgill.edu", 
		  total_applicants: 24325, 
		  percent_admitted: 53,	
		  percent_attending: 41, 
		  range_sat_cr: "640-740", 
		  range_sat_math: "650-720", 
		  range_sat_writing: "650-730", 
		  range_act_comp: "29-32", 
		  average_hs_gpa: "3.52", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Mercer University - Macon", 
		  city: "Macon", 
		  state: "Georgia",	
		  website: "www.mercer.edu", 
		  total_applicants: 3864, 
		  percent_admitted: 69,	
		  percent_attending: 27, 
		  range_sat_cr: "540-630", 
		  range_sat_math: "540-640", 
		  range_sat_writing: "510-620", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.71", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Miami University (OH)", 
		  city: "Oxford", 
		  state: "Ohio",	
		  website: "www.miami.muohio.edu", 
		  total_applicants: 22520, 
		  percent_admitted: 67,	
		  percent_attending: 24, 
		  range_sat_cr: "540-650", 
		  range_sat_math: "580-680", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.72", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Michigan State University", 
		  city: "East Lansing", 
		  state: "Michigan",	
		  website: "www.msu.edu", 
		  total_applicants: 31479, 
		  percent_admitted: 69,	
		  percent_attending: 37, 
		  range_sat_cr: "420-580", 
		  range_sat_math: "550-690", 
		  range_sat_writing: "460-580", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.62", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Michigan Technological University", 
		  city: "Houghton", 
		  state: "Michigan",	
		  website: "www.mtu.edu", 
		  total_applicants: 4905, 
		  percent_admitted: 78,	
		  percent_attending: 33, 
		  range_sat_cr: "520-640", 
		  range_sat_math: "570-688", 
		  range_sat_writing: "493-620", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Middlebury College", 
		  city: "Middlebury", 
		  state: "Vermont",	
		  website: "www.middlebury.edu", 
		  total_applicants: 9109, 
		  percent_admitted: 18,	
		  percent_attending: 39, 
		  range_sat_cr: "630-750", 
		  range_sat_math: "650-740", 
		  range_sat_writing: "650-750", 
		  range_act_comp: "29-33", 
		  average_hs_gpa: "unavailable", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Mills College", 
		  city: "Oakland", 
		  state: "California",	
		  website: "www.mills.edu", 
		  total_applicants: 1827, 
		  percent_admitted: 68,	
		  percent_attending: 17, 
		  range_sat_cr: "540-660", 
		  range_sat_math: "500-610", 
		  range_sat_writing: "520-620", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.54", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Millsaps College", 
		  city: "Jackson", 
		  state: "Mississippi",	
		  website: "www.milsaps.edu", 
		  total_applicants: 1901, 
		  percent_admitted: 47,	
		  percent_attending: 19, 
		  range_sat_cr: "498-630", 
		  range_sat_math: "520-620", 
		  range_sat_writing: "480-610", 
		  range_act_comp: "23-28", 
		  average_hs_gpa: "3.55", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Missouri University of Sciene and Technology", 
		  city: "Rolla", 
		  state: "Missouri",	
		  website: "www.mst.edu", 
		  total_applicants: 3322, 
		  percent_admitted: 82,	
		  percent_attending: 47, 
		  range_sat_cr: "540-670", 
		  range_sat_math: "590-690", 
		  range_sat_writing: "unavailable", 
		  range_act_comp: "25-31", 
		  average_hs_gpa: "3.60", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Monmouth University (NJ)", 
		  city: "West Long Branch", 
		  state: "New Jersey",	
		  website: "www.monmouth.edu", 
		  total_applicants: 5537, 
		  percent_admitted: 78,	
		  percent_attending: 21, 
		  range_sat_cr: "480-560", 
		  range_sat_math: "490-590", 
		  range_sat_writing: "480-570", 
		  range_act_comp: "22-25", 
		  average_hs_gpa: "3.40", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Montana Tech of the University of Montana", 
		  city: "Butte", 
		  state: "Montana",	
		  website: "www.mtech.edu", 
		  total_applicants: 877, 
		  percent_admitted: 88,	
		  percent_attending: 57, 
		  range_sat_cr: "495-635", 
		  range_sat_math: "565-640", 
		  range_sat_writing: "465-600", 
		  range_act_comp: "22-26", 
		  average_hs_gpa: "3.49", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Moravian College", 
		  city: "Bethlehem", 
		  state: "Pennsylvania",	
		  website: "www.moravian.edu", 
		  total_applicants: 1636, 
		  percent_admitted: 80,	
		  percent_attending: 27, 
		  range_sat_cr: "460-580", 
		  range_sat_math: "480-590", 
		  range_sat_writing: "460-580", 
		  range_act_comp: "20-24", 
		  average_hs_gpa: "3.38", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Mount Holyoke College", 
		  city: "South Hadley", 
		  state: "Massachusetts",	
		  website: "www.mtholyoke.edu", 
		  total_applicants: 3732, 
		  percent_admitted: 47,	
		  percent_attending: 30, 
		  range_sat_cr: "620-710", 
		  range_sat_math: "600-720", 
		  range_sat_writing: "620-720", 
		  range_act_comp: "27-31", 
		  average_hs_gpa: "3.66", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Muhlenberg College", 
		  city: "Allentown", 
		  state: "Pennsylvania",	
		  website: "www.muhlenberg.edu", 
		  total_applicants: 5152, 
		  percent_admitted: 46,	
		  percent_attending: 24, 
		  range_sat_cr: "570-670", 
		  range_sat_math: "570-670", 
		  range_sat_writing: "570-670", 
		  range_act_comp: "25-30", 
		  average_hs_gpa: "3.33", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 

		{ name: "Drexel University", 
		  city: "Philadelphia", 
		  state: "Pennsylvania",	
		  website: "www.drexel.edu", 
		  total_applicants: 40586, 
		  percent_admitted: 75,	
		  percent_attending: 10, 
		  range_sat_cr: "540-640", 
		  range_sat_math: "580-680", 
		  range_sat_writing: "530-640", 
		  range_act_comp: "24-29", 
		  average_hs_gpa: "3.60", 
		  superscore_sat: "", 
		  superscore_act: "", 
		  image_url: "" }, 





		]


		School.delete_all

		SCHOOLS.each do |s|
			School.create(s)
		end 
	end 
end 